### ISSUE TITLE
feature: Expose LazyVim types to the LSP

### ISSUE THREAD

**Issue by SirWrexes** [folke/lazydev.nvim#25]
### Did you check the docs?

- [X] I have read all the lazydev.nvim docs

### Is your feature request related to a problem? Please describe.

When using NeoDev, I had access to all the types used in LazyVim, which was really handy because it would help making sure ll specs were entirely compliant with Lazy's requirements, and allowed for neat constraints, e.g. some plugins are fine just being declared as a single string, some _require_ some setup, and depending on that I could use `LazyPluginSpec` for the latter.
Same goes with little helpers functions I've built, e.g. to batch define `LazyKeys[]` in which all keys have the exact same options.
When using NeoDev, all was working fine, but since switching to LazyDev with NeoVim 0.10, all of those types are now unknown to my LSP.

### Describe the solution you'd like

Simply make those types visible to the LSP again.

### Describe alternatives you've considered

I could c/c the type definitions into a `@meta` file in my configs, or download the repo and link the types into somewhere in said configs, but it could be bug-prone in case anything changes and stuff I've imported isn't up to date.

### Additional context

The aforementioned builder function to create an array of `LazyKeys`, as a visual example
![image](https://github.com/folke/lazydev.nvim/assets/5567164/d67022c8-3243-44b7-a3f0-d47bf0c5e144)

**Comment by folke** [comment]
The  simplest way to fix this if you use lazyvim, is to add a comment anywhere that contains the word `LazyVim`.

**Comment by folke** [comment]
So `-- LazyVim` is enough.

**Comment by SirWrexes** [comment]
I am not very well versed in Lua beyond NeoVim configuration, so I really don't know if it is possible to do via some library settings or similar. One such alternative—

Well that was fast, you replied while I was typing. Thanks for the fix.
I am clueless as to what makes this black magic function the way it does but I'll take it!

**Comment by folke** [comment]
I figured that would seem like magic 😅, so here's the explanation:

`lazydev.nvim` will automatically manage your **LuaLS** `Lua.workspace.library`.
Initially it will only contain your globally defined libraries, which for LazyVim, would just be the Neovim runtime.

Whenever you open a file in NEovim that does `require("foobar")`, then lazydev will automatically trace the folder that has that lua module and add the folder as a new workspace library.

In your case, you didn't actually `require("lazyvim")` or something like that, so lazyvim would not have been loaded.

Normally, you would then just add a module annotation somewhere like `---@module 'lazyvim'`, which would like `require` get picked up by **lazydev**.

However, lazydev can also be configured to load certain libraries when certain lua patterns are in your buffer.

The lazydev setup included in LazyVim does:

```lua
 {
    "folke/lazydev.nvim",
    ft = "lua",
    cmd = "LazyDev",
    opts = {
      library = {
        { path = "luvit-meta/library", words = { "vim%.uv" } },
        { path = "LazyVim", words = { "LazyVim" } },
        { path = "lazy.nvim", words = { "LazyVim" } },
      },
    },
  },
```

So that's why writing the word `LazyVim` anywhere in the file would automatically load that library in your workspace.

**Comment by SirWrexes** [comment]
Thanks for the explanation, and for the awesome/clever plugins !
